# Generated by rust2rpm 17
%bcond_without check
%global debug_package %{nil}
 
%global crate vcpkg
 
Name:           rust-%{crate}
Version:        0.2.14
Release:        1
Summary:        Library to find native dependencies in a vcpkg tree
 
# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/vcpkg
Source:         %{crates_source}
# Initial patched metadata
# Exclude unnecessary test and test-data files
Patch0:         vcpkg-fix-metadata.diff
 
ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif
 
BuildRequires:  rust-packaging
 
%global _description %{expand:
Library to find native dependencies in a vcpkg tree at build time in order to
be used in Cargo build scripts.}
 
%description %{_description}
 
%package        devel
Summary:        %{summary}
BuildArch:      noarch
 
%description    devel %{_description}
 
This package contains library source intended for building other packages
which use "%{crate}" crate.
 
%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/
 
%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch
 
%description -n %{name}+default-devel %{_description}
 
This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.
 
%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml
 
%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
%generate_buildrequires
%cargo_generate_buildrequires
%build
%cargo_build
%install
%cargo_install
%if %{with check}
%check
%cargo_test
%endif
